### ISSUE TITLE
Add x-editable example fields for ag-demo app

### ISSUE THREAD

**Issue by aShevc** [9ci/angle-grinder#251]
For example we could make orgTab fields (name and num) changable with x-editable 
http://localhost:8080/ag-demo/orgTabs/index#/4

**Comment by basejump** [comment]
1. make it so that the default home page (http://localhost:8080/ag-demo/) goes to localhost:8080/ag-demo/orgTabs/
2. I'll give demo of x-editable in RCM
3. will send sample code
4. we will change the address tab to have a panel and use x-editable. 
5. add new field to domain for addressDate
6. add field to panel for addressDate
7. make sure we have tests for it, integration and/or unit
