### ISSUE TITLE
demo has broken parts with new boot strap

### ISSUE THREAD

**Issue by basejump** [9ci/angle-grinder#261]
see here http://screencast.com/t/K7DU4FFCB

**Comment by basejump** [comment]
also I cannot run the ```grunt server```
![image](https://cloud.githubusercontent.com/assets/187726/10378258/88bfbc9c-6dcd-11e5-9554-b69b20d3851a.png)

**Comment by alexeyzvegintcev** [comment]
@basejump: due to the fact that some of ui libs were changed(bootstrap) you need to run "bower install" to update them, we do not keep ui components in the repo
Also, I can update grunt bower task to force it update bower components on each action(server, build, etc) but it will take more time on each launch

**Comment by alexeyzvegintcev** [comment]
All fixed in the branch https://github.com/9ci/angle-grinder/pull/265
